apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
    name: fabricfiles
  name: pv-fabric
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes: 
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /var/nfs/general/fabric-files #as per your folder location
    server: <your nfs server ip/host name>
    readOnly: false

---
    
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pvc-fabric
spec:
    selector:
        matchLabels:
            name: fabricfiles
    accessModes:
    - ReadWriteMany
    resources:
        requests:
            storage: 1Gi